let shopItemsData = [{
    id:"kjhgjhiovf",
    name:"Silent Hill 2",
    price: 40.99,
    desc: "Mondo, in conjunction with Konami, is proud to present the premiere vinyl pressing of the soundtrack to the Playstation 2 horror masterpiece: SILENT HILL 2.",
    img: "images/Silent Hill 2 vinyl.jpg",
},
{
    id:"ogkvkfolfj",
    name:"Ultrakill",
    price: 69.99,
    desc: "This is Ultrakill Soundtrack Volume 1: Infinite Hyperdeath 3xLP. You’ll find the music of Ultrakill’s Act 1, a phantasmagoric audio journey sure to take you to the heights of heaven above and the bowels of hell below.",
    img: "images/Ultrakill-Volume-1-Infinite-Hyperdeath.jpg",
},
{
    id:"poihfgudhb",
    name:"Hollow Knight",
    price: 39.00,
    desc: "Ghost Ramp's 2-LP release of Christopher Larkin's original Hollow Knight soundtrack features 26 tracks pressed on two picture discs.",
    img: "images/Hollow Knight vinyl.jpg",
},
{
    id:"qawscvfggff",
    name:"DOOM (2016)",
    price: 40.00,
    desc: "Composed by Mick Gordon, his intense vision channels industrial metal to mirror DOOM’s trademark fast and powerful first-person shooter gameplay across 20 synth and metal-filled tracks.",
    img: "images/DOOM Vinyl.jpg",
},
{   id:"okjnmbughffr",
    name:"Dark Souls III",
    price: 45.75,
    desc: "Composed by Motoi Sakuraba and Yuka Kitamura, Dark Souls orchestral themes will make you dive into the sinister, dark and dramatic world of the series featuring 31 tracks.",
    img: "images/Dark Souls 3 Vinyl.jpg",
},
];